books/book/urls.py
# -*-coding:utf-8-*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'login/$', views.login, name='login'),
    url(r'^search/$', views.search, name='search'),
]

books/books/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('book.urls', namespace='book'))
]

books/book/models.py
# -*-coding:utf-8-*-

from django.db import models
from django.contrib.auth.models import User


class Reader(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=16, unique=True)
    phone = models.IntegerField(unique=True)
    max_borrowing = models.IntegerField(default=5)
    balance = models.FloatField(default=0.0)
    photo = models.ImageField(blank=True, upload_to='images/')

    STATUS_CHOICES = (
        (0, 'normal'),
        (-1, 'overdue')
    )
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=0,
    )

    def __str__(self):
        return self.name

books/book/forms.py
# -*-coding:utf-8-*-
from django import forms


class SearchForm(forms.Form):
    CHOICES = [
        (u'ISBN', u'ISBN'),
        (u'书名', u'书名'),
        (u'作者', u'作者')
    ]

    search_by = forms.ChoiceField(
        label='',
        choices=CHOICES,
        widget=forms.RadioSelect(),
        initial=u'书名',
    )

    keyword = forms.CharField(
        label='',
        max_length=32,
        widget=forms.TextInput(attrs={
            'class': 'form-control input-lg',
            'placeholder': u'请输入需要检索的图书信息',
            'name': 'keyword',
        })
    )


class RegisterForm(forms.Form):
    username = forms.CharField(
        label=u'手机号码：',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'name': 'username',
            'id': 'id_username',
        }),
    )
    name = forms.CharField(
        label=u'名字：',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'name': 'name',
            'id': 'id_name',
        }),
    )
    password = forms.CharField(
        label=u'密码：',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'name': 'password',
            'type': 'password',
            'id': 'id_password',
        }),
    )
    re_password = forms.CharField(
        label=u'重复密码：',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'password',
            'name': 're_password',
            'id': 'id_re_password',
        }),
    )
    email = forms.CharField(
        label=u'电子邮件：',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'name': 'email',
            'id': 'id_email',
        }),
        required=False,
    )

    # photo = forms.FileField(
    #     label=u'头像：',
    #     widget=forms.FileInput(attrs={
    #         'class': 'form-control',
    #         'name': 'photo',
    #         'id': 'id_photo',
    #     }),
    #     required=False,
    # )


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=16,
        label=u'用户名：',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'name': 'username',
            'id': 'id_username',
        })
    )
    password = forms.CharField(
        label=u'密码：',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'password',
            'name': 'password',
            'id': 'id_password',
        }),
    )

books/book/views.py
from django.shortcuts import render
from .forms import SearchForm,  RegisterForm, LoginForm


def index(request):
    """首页"""
    context = dict(
        searchForm=SearchForm
    )
    return render(request, 'book/index.htm', context)


def register(request):
    register_form = RegisterForm
    state = None

    context = dict(
        state=state,
        registerForm=register_form
    )
    return render(request, 'book/register.htm', context)


def login(request):
    login_form = LoginForm
    state = None

    context = dict(
        state=state,
        loginForm=login_form
    )
    return render(request, 'book/login.htm', context)


def search(request):
    pass

books/templates/book/base.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}"/>
    <title>{% block title %}{% endblock %}</title>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/echarts.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!--<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>-->
    <!--<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>-->
</head>
<body>

<nav class="navbar navbar-default navbar-custom nav-head">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">小书屋</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/search/?keyword=_书目列表">书目列表</a></li>
                <li><a href="/statistics/">统计信息</a></li>
                <li><a href="/about/">关于</a></li>
            </ul>

            {% if user.is_authenticated %}

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">用户 {{ ' ' }} {{ user.reader.name }}<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/profile/">个人信息</a></li>
                            <li><a href="#">正在借阅</a></li>
                            <li><a href="/set_password/">修改密码</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="/logout/">登出</a></li>
                        </ul>
                    </li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/login/">登陆</a></li>
                    <li><a href="/register/">注册</a></li>
                </ul>

            {% endif %}
        </div>
    </div>
</nav>

<header class="jumbotron myJumbotron">

    <div class="container">
        <h1>小书屋</h1>
    </div>

</header>

{% block content %}
{% endblock %}

</body>
</html>

books/templates/book/index.htm
{% extends 'book/base.htm' %}
{% block title %}小书屋{% endblock %}
{% block content %}

    <div class="container myContainer">
        <form action="/search" method="GET">
            <div class="row col-lg-7 col-lg-offset-3">

                {% for radio in searchForm.search_by %}
                    <div class="radio-inline">
                        {{ radio }}
                    </div>
                {% endfor %}

                <div class="input-group">
                    {{ searchForm.keyword }}
                    <span class="input-group-btn">
                        <button class="btn btn-default btn-lg btn-info" type="submit">查找</button>
                    </span>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

books/templates/book/login.htm
{% extends 'book/base.htm' %}

{% block title %} 请登陆 {% endblock %}

{% load static %}
<link href="{% static 'css/signin.css' %}" rel="stylesheet">

{% block content %}

    {% if state == 'not_exist_or_password_error' %}
        <div class="col-md-2 col-md-offset-5">
            <div class="alert alert-warning">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <h2>用户不存在或密码错误</h2>
            </div>
        </div>
    {% endif %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">


                <form method="POST" role="form" class="form-horizontal" action="{%url 'book:login' %}">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">请登陆</h1>

                    {% for field in loginForm %}
                        <div class="form-group">
                            <label class="col-md-3 control-label">{{ field.label }}</label>
                            <div class="col-md-9">
                                {{ field }}
                            </div>
                        </div>
                    {% endfor %}


                    <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                            <button class="btn btn btn-primary btn-block" type="submit">登陆</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

books/templates/book/register.htm
{% extends 'book/base.htm' %}

{% block title %} 注册 {% endblock %}

{% load static %}
<link href="{% static 'css/signin.css' %}" rel="stylesheet">

{% block content %}

    {% if state %}
        <div class="col-md-2 col-md-offset-5">
            <div class="alert alert-warning">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                {% if state == 'success' %}
                    <h2> 注册成功！ </h2>
                {% elif state == 'repeat_error' %}
                    <h2> 密码重复错误 </h2>
                {% elif state == 'empty' %}
                    <h2> 密码不能为空 </h2>
                {% elif state == 'user_exist' %}
                    <h2> 户已经存在 </h2>
                {% endif %}
            </div>
        </div>
    {% endif %}

    <div class="container myContainer">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

                <form method="POST" action="/register/" role="form" class="form-horizontal"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">请注册</h1>

                    {% for field in registerForm %}
                        <div class="form-group">
                            <label class="col-md-3 control-label">{{ field.label }}</label>
                            <div class="col-md-9">
                                {{ field }}

                                <!--{% if field.auto_id == 'id_username' %}-->
                                    <!--<span class="help-block">用于登陆，手机号码</span>-->
                                <!--{% endif %}-->
                            </div>
                        </div>
                    {% endfor %}


                    <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                            <button class="btn btn btn-primary btn-block" type="submit">注册</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>


{% endblock %}